defaults:
  - _self_
  - task: pt

# Experiment args
mode: 'pt'
device: gpu
eval_only: false
predict_only: false
seed: 2137

model:
  name: 'google/t5-v1_1-base'
  checkpoint_path: ''
  dropout: 0.0
  random_init: true
  compile: false # Pytorch 2.0

data:
  input_length: 512
  mlm_probability: 0.15
  mean_noise_span_length: 3.0
  num_workers: 0

optim:
  name: adamwscale
  base_lr: 2e-2
  batch_size: 144
  total_steps: 65536
  epochs: -1 # If it's > 0 it overwrites total_steps
  warmup_steps: 10000
  lr_scheduler: cosine
  lr_scheduler_checkpoint_path: '/Users/seven/Documents/ai/nanoT5/nanoT5/checkpoint/pt/scheduler.bin'
  weight_decay: 0.0
  grad_clip: 1.0
  grad_acc: 2
  final_cosine: 1e-5
  checkpoint_path: '/Users/seven/Documents/ai/nanoT5/nanoT5/checkpoint/pt/optimizer.bin'

eval:
  every_steps: 300 # Don't eval
  steps: 100

checkpoint:
  every_steps: 500
  path: ./checkpoint
  save_step: False # when True, saves every step instead of the latest checkpoint

logging:
  neptune: false
  neptune_creds:
    project:
    api_token:
    tags:
  every_steps: 100
  run_id: 'NAN-43'
  grad_l2: true
  weights_l2: true

hydra:
  job:
    chdir: True
  run:
    dir: ./logs/${now:%Y-%m-%d}/${now:%H-%M-%S}
